#include <boost\utility\binary.hpp>

#ifndef __ROVERCOMMANDS__
#define __ROVERCOMMANDS__

#define ROVER_INTERNAL_COMMAND_NOCOMMAND      BOOST_BINARY (10000000)
#define ROVER_INTERNAL_COMMAND_SETLWHEEL      BOOST_BINARY (10000001)
#define ROVER_INTERNAL_COMMAND_SETRWHEEL      BOOST_BINARY (10000010)
#define ROVER_INTERNAL_COMMAND_GETDISTANCE    BOOST_BINARY (10000011)
#define ROVER_INTERNAL_COMMAND_QDISTREADY     BOOST_BINARY (10000100)
#define ROVER_INTERNAL_COMMAND_RETDISTANCEH   BOOST_BINARY (10000101)
#define ROVER_INTERNAL_COMMAND_RETDISTANCEL   BOOST_BINARY (10000110)

#define ROVER_INTERNAL_COMMAND_CONFIRMED      BOOST_BINARY (11111111)
#define ROVER_INTERNAL_COMMAND_UNKNOWN        BOOST_BINARY (11111110)
#define ROVER_INTERNAL_COMMAND_QUERY          BOOST_BINARY (11111101)
#define ROVER_INTERNAL_COMMAND_DISTREADY      BOOST_BINARY (11111100)
#define ROVER_INTERNAL_COMMAND_DISTNREADY     BOOST_BINARY (11111011)
#define ROVER_INTERNAL_COMMAND_BADSTATE       BOOST_BINARY (11111010)
#define ROVER_INTERNAL_COMMAND_TOOMANYNOC     BOOST_BINARY (11111001)

#define ROVERMESSAGE_VERSION 0x01

#define ROVER_STOP         0x00
#define ROVER_LEFT         0x01
#define ROVER_RIGHT        0x02
#define ROVER_FORWARD      0x03
#define ROVER_BACK         0x04
#define ROVER_HORN         0x05
#define ROVER_SETTRIM      0x06
#define ROVER_GETDISTANCE  0x07

struct _sWord {
  unsigned char low;
  unsigned char high;
};
  
union word {
	_sWord sWord;
	unsigned int val;
};

struct ROVERMESSAGE {
	ROVERMESSAGE() : 
		ver(ROVERMESSAGE_VERSION), cmd(ROVER_STOP)
	{};
	ROVERMESSAGE (const ROVERMESSAGE * msg) {
		ver = msg->ver;
		cmd = msg->cmd;
		data.val = msg->data.val;
	}
	unsigned char ver;
	unsigned char cmd;
	word data;
};

#endif